# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Systems Genomics Summit 2021"
email: "gensysbioconf@nuigalway.ie"
description: "Systems Genomics Summit is a student-led genomics conference scheduled for December 2021 in Galway, Ireland. We are looking forward to hosting world-class speakers working on research covering different areas in genomics and systems biology. We will have talks covering a wide range of themes, including Methods Development and Systems Biology, Metagenomics and Agrigenomics, Evolution and Population Genomics, and Health and Disease Genomics. In previous years, this conference was hosted at University College Dublin (online in 2020!) as the Computational Genomics and Molecular/Systems Biology Summit."
baseurl: "/main"
url: "https://systemsgenomicssummit.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "G-EXJ1QJR4T0"
googleAnalyticsSiteUrl: "systemsgenomicssummit.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "CRT Genomics Data Science"
organizerAlternateName: "SFI Centre for Research Training in Genomics Data Science"
organizerDescription: "Systems Genomics Summit is a student-led genomics conference scheduled for December 2021 in Galway, Ireland."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "genomics, genetics, bioinformatics, data science, ireland, research, systems, biology, biotech"
twitterAccount: "@SysGenSummit"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "" # call for papers #Submit Abstract button href
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/team/", text: "About"}
   # - {permalink: "/blog/", text: "Registration"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Sponsors"}
bottomNavigationLinks:
 - {link: "https://forms.gle/fa23NKbBYhAAZsKq6", text: "Register"} # link to abstract submission
rightNavigationButtons:
 - {link: "https://forms.gle/fa23NKbBYhAAZsKq6", text: "Register"} # link to abstract submission

# Hero Block
heroImage: "hero.jpg" # edit size of symp text
heroTitle: "Systems Genomics Summit"
eventDate: "Dec 2nd - 3rd 2021"
typeoutTextValues: '""'
typeoutFallback: "2021"
# heroButtons: # comment to remove buttons
 # - {link: "https://bit.ly/dfua-c4p", text: "Submit abstract"}
 # - {permalink: "/#tickets", text: "Register"}

# About Block
aboutTitle: ""
aboutBlock:
 - {title: "Student-led", image: "grad.jpeg", text: "Replace image. The format and speakers for the summit have been carefully crafted by Bioinformatics and Systems Biology students of UCD and the SFI CRT in Genomics Data Science." }
 - {title: "Themes", image: "genomics.jpg", text: "The symposium will highlight research that falls under the umbrella of computational genomics and systems biology, with a focus on four broad research themes: Methods development and systems biology, Metagenomics and agrigenomics, Evolution and population genomics, and Health and disease genomics" }
 - {title: "Format", image: "systems-biology-1.jpg", text: "The symposium will be an in-person event in Galway this December, with two days of talks. We will have six keynote speakers, along with poster sessions and sponsor talks." }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 6
rockstarSpeakersTitle: "Speakers"
rockstarSpeakersButtonText: "Read more about our speakers"

# Latest News Block
latestNewsTitle: "Background"

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "removing"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "removing"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "removing"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "removing"}


# Location Block
# locationBlockTitle: "Location"
# eventLocationName: "NUI Galway"
# eventLocationLink: "http://www.nuigalway.ie/"
# eventStreetAddress: "University Road"
# eventAddressLocality: "Galway"
# eventAddressLocalityRegion: "Galway"
# eventPostalCode: "H91W5P7"
# eventAddressCountry: "Ireland"
# eventStartTime: "2021-12-02T10:00"
# eventDoorTime: "10:00"
# eventEndTime: "2021-12-03T20:00"
# eventPlaceCoordinates: "53.278671450000004, -9.059193370039853"
# mapCenterCoordinates: "53.278671450000004, -9.059193370039853"
# mapMobileCenterCoordinates: "53.278671450000004, -9.059193370039853"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "NUIG_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Salthill Hotel Galway"
venueFeatures: ["Located close to Galway city centre", "Food provided"]
#venueFeatures: ["Host university of SFI CRT in Genomics Data Science", "Located close to Galway city centre", "Food provided"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Join the conversation"
twitterHashTag: "SysGen21"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizers"
partnersTitle: ""
#partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration IS A TEST. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: ""
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks and lunch. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Student"
  price: "20"
  priceCurrency: "EUR"
  # ticketsNumber: "150"
  featured: true
# ribbon: "-5%"
  buyButtonLink: "eventbrite.com"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in."
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  #  validFrom: "2014-08-25T10:00"
  # validThrough: "2014-09-30T23:59"
 -
  name: "Academic/Industry"
  price: "40"
  priceCurrency: "EUR"
  # ticketsNumber: "100"
  # ribbon: "-20%"
  featured: true
  buyButtonLink: "eventbrite.com"
  buyButtonText: "Buy Now"
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  # validFrom: "2014-10-01T00:00"
  #validThrough: "2014-10-23T23:59"
  # disabled: true

  #-
  # name: "Commercial"
  # price: "50"
  # priceCurrency: "EUR"
  # ticketsNumber: "50"
  # buyButtonLink: "http://dfua.ticketforevent.com/"
  # buyButtonText: "Buy Now"
  # additionalInfo: "Requires a valid student ID at the conference check in."
  # ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  # validFrom: "2014-08-20T10:00"
  # validThrough: "2014-10-23T23:59"
  # soldOut: true
  # soldOutText: "Sold Out"

# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/SysGenSummit", icon: "twitter"}
 #- {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://genomicsdatascience.ie/", text: "SFI Genomics CRT"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gensysbioconf@nuigalway.ie", text: "gensysbioconf@nuigalway.ie"}
# Blog
blogTitle: "Origin and Past Events"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Systems Genomics Summit 2021 is organized by a committee of PhD students from four Irish universities (UCD, TCD, NUIG, and UCC). We are supported by the PhD programs in SFI Center for Research Training in Genomics Data Science and the UCD Bioinformatics. Having all started our PhDs mid-pandemic, we look forward to welcoming you to a fantastic in-person event in Galway this December! 

We are Rasha Shraim (TCD), Shane Crinion (NUIG), Cosmin Tudose (UCD), Tembi Fashina (RCSI), Padraic Heneghan (UCD), Donal O'Shea (NUIG), Anjan Venkatesh (UCD), Marina Villacampa Fernandez (UCD), and Sai Ravi Chandra Nori (UCC)."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "twitter-feed.jpg"
directionDetailsTitle: "Get around Galway"
directionDetailsCards:
 - {title: "From the Airport", information: 'Galway is a 2.5 hour journey from Dublin Airport. Many care hire options are available at the <a href="https://www.dublinairport.com/to-from-the-airport/car-rental">airport website</a>.'}
 - {title: "Public Transit", information: 'Citylink and GoBus offer a bus service from Dublin city and Dublin Airport to Galway city. Galway city to Salthill is about a 10 minute drive/bus journey and is serviced by the 401 bus. The bus stop is located beside The Hardiman Hotel in Eyre Square. A taxi can also be picked up at this location from Big O Taxis.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://www.salthillhotel.com/", text: "Salthill Hotel"}
     - {link: "https://www.galwaybayhotel.net/", text: "The Galway Bay Hotel"}
     - {link: "https://www.jurysinns.com/hotels/galway", text: "Jurys Inn"}
     - {link: "https://www.thehardiman.ie/", text: "The Hardiman"}
   
# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
